### ISSUE TITLE
Installing Kite via VS Code plugin doesn't work on Windows [10]

### ISSUE THREAD

**Issue by adamsmith** [kiteco/vscode-plugin#104]
Steps to reproduce:

1) on a fresh Windows 10 VM, install VS Code
2) install the "kite" plugin
3) click "Reload" so VS Code reloads and the plugin loads

Expected behavior: the Kite install process kicks off

Observed behavior: "Kite Install" tab is messed up

(I didn't test this on other versions of Windows)

![screen shot 2018-03-09 at 4 47 49 pm](https://user-images.githubusercontent.com/87728/37236452-6b62dda8-23bc-11e8-9379-0c40d6f070f4.png)

**Comment by jansorg** [comment]
I'm seeing this as well...

**Comment by adamsmith** [comment]
@abe33 given your fix, has this been an issue since we first launched, or if not, how long has it been an issue?  (This is useful to know as we think about how much we need to improve our QA efforts to catch these kinds of bugs.)

**Comment by adamsmith** [comment]
Confirmed fixed, thanks!
