### ISSUE TITLE
Whitelist notifications only showing one action

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#109]
The notification which is shown for non-whitelisted files is showing just one action button "Whitelist ..." instead of the other options which were displayed previously.
I think that this changed with the update to VSCode 1.21. 

Is there a way to add the other actions back in?
![screenshot_20180312_185311](https://user-images.githubusercontent.com/11473063/37300593-9e8391d4-2626-11e8-80b1-53d6d0041211.png)

**Comment by abe33** [comment]
@jansorg  There was always one action, it's just that previously the default close action was rendered as a button and we were using that close action as a implicit blacklist action. That's still the case with the current version, so for me it's either a wontfix (the behavior hasn't changed) or we should make notification consistent with all editors.

**Comment by jansorg** [comment]
@abe33 Thanks, I'll look into an update to the spec. Reassigning to me.

**Comment by jansorg** [comment]
not needed anymore
