### ISSUE TITLE
Icon in plugin list looks like that it's disabled

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#110]
@mwichary I'm assigning this to you, feel free to reassign.

The actual icon is: https://github.com/kiteco/vscode-plugin/blob/master/logo.png

I just noticed that the contrast in the list of plugins is quite low. At first I assumed that it's disabled for some reason...
![screenshot_20180312_190137](https://user-images.githubusercontent.com/11473063/37301040-ccaf6474-2627-11e8-9aaf-d81c1e426b56.png)

**Comment by mwichary** [comment]
It probably works great in a light theme. ;·)
