### ISSUE TITLE
Standardize commands

### ISSUE THREAD

**Issue by dhung09** [kiteco/vscode-plugin#127]
Refer to [this doc](https://kite.quip.com/HinNAHAoaVpH/Kite-commands-in-editors) to see the in-depth discussion of these commands.

To summarize, these commands (and only these commands) should be implemented:

- [x] Kite: Docs at cursor
- [x] Kite: Open sidebar
- [x] Kite: Open Error Rescue sidebar
- [x] Kite: Open Copilot
- [x] Kite: Search
- [x] Kite: General settings
- [x] Kite: Permissions
- [x] Kite: Status
- [x] Kite: Help
  - This should link to https://help.kite.com/category/46-vs-code-integration

**Comment by abe33** [comment]
Commands to close a tab can't be implemented in VSCode. Same thing with the editor plugin settings, users can choose between workspace-limited or global settings and we have no way of knowing which one have been used before and is relevant at a given point in time for a given project.

**Comment by mwichary** [comment]
@abe33 as for Settings, an alternative might be opening a pane where we just talk about the settings and how to access them.

There is a view that already has most of it:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/2061609/39534395-562a21fe-4de6-11e8-9c55-9cb75a1f2b7e.png">

Given how sparse VS Code settings are today, I don’t think I would worry much about implementing that; this is more of a general comment. If VS Code’s settings evolve more into actually affecting the UI of the plugin (similarly to Atom or IntelliJ), it might be worth revisiting.

**Comment by jansorg** [comment]
Already merged.
