### ISSUE TITLE
Use "call.funcName" instead of "call.callee.repr" for popular patterns in signature completions

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#140]
Spec update: https://kite.quip.com/BwMIAmafCAQs/Behavioral-Specification#HVeACAmkuAw
The latest version of kited already returns this property.

The rendering of popular patterns changed. This applies only to signature completions.
Now "call.funcName" should be used instead of "call.callee.repr".
If property `funcName` is not available, then the rendering should fallback to `callee.repr`. This is to support old versions of kited. This fallback could be remove in a few weeks when we're certain that most users have a current version of Kite.

Related issue in Kite: https://github.com/kiteco/kiteco/issues/4557

Test code:
```python
import django
django.db.models.fields.CharField()
```

**Comment by abe33** [comment]
@jansorg We can't render popular patterns in signature completions in VSCode so I guess it's a wontfix.

**Comment by jansorg** [comment]
Closing, as it's not supported in VSCode.
