### ISSUE TITLE
Hover panel links don't do anything

### ISSUE THREAD

**Issue by dhung09** [kiteco/vscode-plugin#143]
Clicking on the "web" or "more" links in the hover panel does not do anything. However, using the command palette does. Probably the command names were not kept consistent in these codepaths

**Comment by abe33** [comment]
Sadly, nothing was changed in that part recently, the command naming haven't been changed at all (display label and command names are separated things). The weird thing here is if I create a new command and put a link to that command in a hover it still don't work (following the official documentation and examples), and I can't find a single issue/pr that relates to a change in that part in VSCode recently, I may have to dig into the sources and commits history.
