### ISSUE TITLE
Use kite://home instead of /clientapi/sidebar/open

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#147]
There's a new way to open the Copilot. Please use `kite://home` instead of `GET /clientapi/sidebar/open`.

Spec: https://kite.quip.com/HinNAHAoaVpH/Commands-in-editors#DPAACAbII8L

**Comment by abe33** [comment]
we may have an issue here, not sure why, but in VSCode we had some `kite://` calls not properly opening the copilot so we had to make a request to `/clientapi/sidebar/open` to make sure the copilot is open before using the `kite://` protocol

**Comment by abe33** [comment]
I confirm, using `kite://home` does not open the copilot from within VSCode, the whole `kite://` protocol seems to only work from VSC when the copilot is already open. We've been stuck for a while with @dbratz1177 on this back when I was in SF and we couldn't figure why this failed to work.
