### ISSUE TITLE
Broken reset password link

### ISSUE THREAD

**Issue by dhung09** [kiteco/vscode-plugin#161]
A user reported that he clicked on "reset password" and was taken to `https://kite.com/account/resetPassword/request?email={ email }`

Seems like [this line of code](https://github.com/kiteco/vscode-plugin/blob/65134be52dad80aa3ae5c8afb42c1915cb66ccd2/assets/js/login.js#L10) is causing this.

The URL should be `https://kite.com/reset-password?email={ email }`

**Comment by jansorg** [comment]
Fix already on master
