### ISSUE TITLE
not recognizing kite engine login

### ISSUE THREAD

**Issue by dbratz1177** [kiteco/vscode-plugin#169]
Surfaced in QA. The image below describes what's going on. Feel free to close if this is already a known issue

![image](https://user-images.githubusercontent.com/6146901/47463906-6f7af800-d79c-11e8-84fa-2f64b7e9deee.png)

**Comment by abe33** [comment]
@dbratz1177 I don't reproduce on my computer, but do you think it could be the same kind of issue you fixed in the atom plugin regarding login notifications?

**Comment by dbratz1177** [comment]
possibly could. I'll revisit that PR, and try to reproduce this on my machine. If neither turns up anything, I'll close this issue

**Comment by dbratz1177** [comment]
@abe33 my investigations seem to indicate that the issue is along the lines of:
1. VSCode is opened with plugin running and Kite logged out
2. Login via Copilot
3. Notification doesn't disappear

I'm sure you've ran into the fact that VSCode doesn't support programmatic dismissals of notifications (e.g. https://github.com/Microsoft/vscode/issues/48960), so it doesn't seem like something we can actually fix

**Comment by abe33** [comment]
Oh, thanks for the explanation, and yes, notifications can't be dismissed programmatically.
