### ISSUE TITLE
Kite logo in VS Code far too large

### ISSUE THREAD

**Issue by adamsmith** [kiteco/vscode-plugin#175]
![screen shot 2018-11-09 at 4 38 47 pm](https://user-images.githubusercontent.com/87728/48295138-06eb7680-e43e-11e8-8aa9-b1b2ca147f7a.png)

**Comment by abe33** [comment]
Hi @adamsmith, it looks like the stylesheets were not loaded, can you tell me which version of VSCode  you're running, as I don't reproduce using latest version. Also, there's #175 that will switch the status and the install to the new webview API (see also #172) so maybe it'll be worth checking that branch as well just to make sure the issue doesn't occurs with the new version on your vscode install.
Feature-wise that new branch changes nothing, it only changes the api we use to display custom views.

**Comment by jansorg** [comment]
@abe33 I've tested master and the release versions with the latest stable version of VSCode on macOS and Windows. I'm not seeing the large icon here.
