### ISSUE TITLE
Indexing won't stop.

### ISSUE THREAD

**Issue by megravity** [kiteco/vscode-plugin#178]
So I just installed Kite and wanted to try it really quick. So I fired up VSCode set everything up and opened an empty .py file. After indexing for about 45 minutes I first restarted my computer with no success, then I reinstalled Kite, still no success. I also uninstalled the VSCode plugin and installed it via the extension marketplace and still no success...

I'm on OSX 10.13.6 High Sierra
I also looked for logs or something like it but couldn't find anything.
Google also could not help.

**Comment by dhung09** [comment]
Hi @megravity, can you send the contents of your Kite log to feedback@kite.com so we can help debug? On macOS the logs are located at `~/.kite/logs/client.log`.

**Comment by megravity** [comment]
Hi @dhung09 I'm away for the weekend, but I'll quickly try to recreate the problem on my Macbook (Running Mojave on it tho). If I can't recreate the issue, you'll get the log on Monday!

**Comment by megravity** [comment]
Well of course it works on my Laptop now... 
Do you think it's related to the OS? Nevertheless, will get back to you on Monday! Thanks for the quick response.

**Comment by dhung09** [comment]
It may be related to the OS. In any case, we'll keep an eye out for your logs if necessary. I'm going to close this issue for now though.
