### ISSUE TITLE
kite can not find vscode

### ISSUE THREAD

**Issue by seanmars** [kiteco/vscode-plugin#2]
Refer to the title, kite can not find vscode, even installation the package manually.

vscode version: 1.11.2

**Comment by jansorg** [comment]
@seanmars Do you still see this? 
We've been adding many improvements to the plugin in the meantime and think that this should work now.

**Comment by seanmars** [comment]
Hi, i don't have use kite now. So i can't check it now.

**Comment by jansorg** [comment]
@seanmars Thanks for the reply. We're closing this now. If it turns out that this still happens for you please reopen this issue.
