### ISSUE TITLE
plugin is autostarting kite after startup (probably after  status checks)

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#203]
Tested on Windows 10

1. stop kite
1. start vscode
1. kite will be automatically started
1. stop kite
1. work in a Python file in VSCode
1. --> Kite will be started again

Kite should only be started automatically at startup. Automatic starting later on must not be done. (At least this is already unnerving me as it complicates testing)

**Comment by its-dhung** [comment]
Fixed by #207
