### ISSUE TITLE
Should I disable Microsoft Python extension to use Kite autocomplete?

### ISSUE THREAD

**Issue by off99555** [kiteco/vscode-plugin#209]
From this message: `Note: If you have the Microsoft Python extension installed, Kite will not be able to show you information on function signatures.`

Do I miss on something if I disable Microsoft Python extension to use function signatures from Kite instead?
What is your recommendation?

**Comment by its-dhung** [comment]
Like Kite, Microsoft's Python extension provides information on function signatures. We've worked hard on our static analysis and are still improving it, so we think in some cases, Kite will be able to provide information on functions whereas the MS Python extension can not. However, with the MS Python extension installed, you would not be able to see that information from Kite.

Nonetheless, the MS Python extension provides some other features that Kite doesn't have such as linting and debugging. Therefore, from a total usability standpoint, I would not recommend disabling the MS Python extension. We're working on making sure Kite works well with the MS Python extension, so we'll find a way to support this use case soon!
