### ISSUE TITLE
100% cpu & fork bomb

### ISSUE THREAD

**Issue by ofek** [kiteco/vscode-plugin#210]
Win 10 pro - i5

I just tried the plugin and it is unusable as merely opening vscode causes `WMI Provider Host` to maintain near 100% cpu and vscode processes endlessly spawn. Even after 10 min everything is still locked up, requiring a power cycle

![capture](https://user-images.githubusercontent.com/9677399/52373217-1facfd80-2a28-11e9-8521-5439b10aa28f.PNG)

~3 spawned processes per second
![capture](https://user-images.githubusercontent.com/9677399/52373447-a5c94400-2a28-11e9-8eb5-c9b4c813c903.PNG)

**Comment by its-dhung** [comment]
Hi @ofek, so sorry for the inconvenience! We'd love your help figuring out what's causing this.

1. Download Microsoft's [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)
2. Start VS Code to get the undesired behavior running
3. Run the Process Monitor and accept the default filters
4. Wait a few seconds while events are captured
5. Select `File` → `Capture Events` to toggle off capture
6. Select `File` → `Save` and then `Events to save: All events` + `Format: Native Process Monitor Format (PML)`
7. Send us the resulting file to feedback@kite.com and we investigate and debug for you

Thanks for reporting this bug and for your help tracking it down!

**Comment by metalogical** [comment]
Closed due to age. This should hopefully no longer be an issue.
