### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rljonesiii** [kiteco/vscode-plugin#216]
- Issue Type: `Performance`
- Extension Name: `kite`
- Extension Version: `0.77.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rjones/kiteco.kite-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by its-dhung** [comment]
Hi @rljonesiii, thanks for taking the time to write in! Can you please attach the CPU profile listed above (`/Users/rjones/kiteco.kite-unresponsive.cpuprofile.txt`) either in this GitHub issue or in an email to support@kite.com? We'd love to help debug this issue!

**Comment by metalogical** [comment]
Closed due to age.
