### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mbusch-regis** [kiteco/vscode-plugin#217]
[kiteco.kite-unresponsive.cpuprofile.txt](https://github.com/kiteco/vscode-plugin/files/2997249/kiteco.kite-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `kite`
- Extension Version: `0.77.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mbusch/kiteco.kite-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by its-dhung** [comment]
Thanks for reporting this issue @mbusch-regis. We're investigating.

**Comment by adamsmith** [comment]
Hi @mbusch-regis, do you recall any information about what you were doing when you got this? For example, were you editing a Python file, editing a large non-Python file, starting VS Code, shutting it down, etc?

Thanks!

**Comment by mbusch-regis** [comment]
Hi Adam,

I’d just started VS Code, although I think it was trying to also open a large data file at the same time.

Mike

**Comment by edzkite** [comment]
Hi Mike,

Apologies for the lack of updates. To further assist you, would you mind telling us if you've been able to reproduce the issue, and with what frequency? If so, how?

Any additional information would be much appreciated!

Best,
Ed

**Comment by mbusch-regis** [comment]
Hi Ed,

Unfortunately, I have not. Actually, I do > 80% of my work in Jupyter notebooks and so can’t use Kite. When I encountered the error, I was trying out the combo of Kite + VS Code to demo Kite functionality if I ever need to write a library, program, etc.

My feeling is, unless you’ve see a similar problem from other users, you can drop this issue.

Regards,
Mike

**Comment by metalogical** [comment]
Closed due to age.
