### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by akharrou** [kiteco/vscode-plugin#226]
- Issue Type: `Bug`
- Extension Name: `kite`
- Extension Version: `0.82.0`
- OS Version: `Darwin x64 17.5.0`
- VSCode version: `1.34.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 78,
		"activateCallTime": 7,
		"activateResolvedTime": 3,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Unable to find Kite application install using mdfind"
		},
		{
			"name": "Error",
			"message": "Unable to find Kite application install using mdfind"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'focus' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'selectionChanged' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'selectionChanged' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'selectionChanged' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'selectionChanged' of undefined"
		}
	]
}
```

**Comment by edzkite** [comment]
Hi! Thanks for alerting us to this issue. To help assist you further, could you let us know if you have the [Kite Engine](https://kite.com) (it's separate from the plugin itself) installed on your system?
