### ISSUE TITLE
VS Code hover panel: links are flaky

### ISSUE THREAD

**Issue by jlozano** [kiteco/vscode-plugin#23]
Reported by @adamsmith 

Moving your mouse around over the 'web' and 'more' links: sometimes the mouse is over the links but the cursor is a pointer and clicking doesn't work.

@abe33 Adam or I are happy to help repro if needed!

**Comment by abe33** [comment]
Yes, I've been experiencing that as well, but there's nothing we can do at our level, we can't mess with VSCode UI in any way. Using images would be an option if we were able to detect which kind of theme is used (light, dark, high-contrast), but it seems there's no API for that. I also tried to find a way to increase the size of the text, but except for titles there's nothing in markdown that allow us to do that, and when using titles we end up with margins above and below our links that we can't remove.

**Comment by adamsmith** [comment]
I don't seem to be able to repro so maybe VS Code fixed this
