### ISSUE TITLE
command kite.* commands not found

### ISSUE THREAD

**Issue by rithvikvibhu** [kiteco/vscode-plugin#236]
I installed Kite through the graphical installer and reloaded vscode.

None of the kite commands work from the command palette. For example:
Selecting `Kite: Help` gives an error `command "kite.help" not found`.

This happens for all Kite commands. I even reinstalled through vscode extensions. Same issue.

**Comment by yashrajjain726** [comment]
It is because , commands of kite can be run only in the command palette of code editors,as shown in the below screenshot.
![Screenshot (90)](https://user-images.githubusercontent.com/53373012/82760358-a568de00-9e10-11ea-8154-2de3610ca3f8.png)
If fine with the results , please close the issue .

**Comment by yashrajjain726** [comment]
@rithvikvibhu Please Close the Issue if resolved else ask your doubt .

**Comment by rithvikvibhu** [comment]
As mentioned in the issue description, the commands were listed just like in your screenshot, but selecting any of them gives an error `command "kite.help" not found` (or similar) in the bottom-right notification area.

In hindsight, I could've attached screenshots.

I no longer use Kite and can't verify this year-old issue. Closing this issue.
