### ISSUE TITLE
the windows flashed for a moment

### ISSUE THREAD

**Issue by muyiyiyi** [kiteco/vscode-plugin#246]
when i use kite, the vscode and pycharm ,open an new python file, the cmd awindow flashes a moment , and disappear quickly。
![xxx](https://user-images.githubusercontent.com/45055678/64431401-edae6780-d0ec-11e9-9af1-ad0d8d18c9e0.gif)

**Comment by its-dhung** [comment]
Hi @muyiyiyi, can you share:

1. What version of the Kite application you're running?
2. What version of VS Code you're running?
3. What version of the Kite VS Code extension you're running?

If you can reproduce this, can you also send us the file located at `C:\Users\< your name >\AppData\Local\Kite\logs\client.log`? You can email the file to feedback@kite.com.

**Comment by Khalilsqu** [comment]
I experienced the same thing but it no longer happens

**Comment by its-dhung** [comment]
This has been fixed in a previous release!
