### ISSUE TITLE
Activating extension 'kiteco.kite' failed

### ISSUE THREAD

**Issue by mohamedluay** [kiteco/vscode-plugin#250]
I have installed kite with the .dmg installer found on the website and followed the steps from there. Now I have problem with running the extension on VSCode, When I have toggled developer tools, it showed me the following error 👇.

`Activating extension 'kiteco.kite' failed: Cannot find module '/Users/mohamedluay/.vscode/extensions/kiteco.kite-0.98.0/dist/kite-extension'.`

`Activating extension `kiteco.kite` failed:  Cannot find module '/Users/mohamedluay/.vscode/extensions/kiteco.kite-0.98.0/dist/kite-extension'`

I did cd to the path and looked myself for the mentioned file and as expected, it didn't exist, only **kite-extension.js.map** file is found. 

N.B
My OS: Mac Os Catalina Version 10.15
Vscode Version: 1.38.1

**Comment by metalogical** [comment]
Closed due to age. This should hopefully no longer be an issue.
