### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by voldikss** [kiteco/vscode-plugin#261]
Hi there. Conguratulations for your Kite completion engine and thanks for your development!

I am a Vim user(I use coc.nvim for code completion) and I've tried your [vim-plugin](https://github.com/kiteco/vim-plugin), it is pretty cool! However, that means I have to drop coc.nvim, which I'am unwilling to do. Therefore, I developed a coc-kite, which is a coc.nvim extension for Kite. It can gather completion from Kite engine and send them to coc's completion candidates. It works pretty well for me and I am planning to put it on the GitHub. However I noticed your [LICENSE](https://github.com/kiteco/vscode-plugin/blob/master/LICENSE) in this repo and it has a very strict limitation. 

The truth is, coc-kite is developped using typescript. I've grabbed some code from this repo and re-write them using typescript. Now the problem is, could I have a change to public it on GitHub? If yes, what should I do? I don't know if it is correct behavior to request a permission in a GitHub issue, if not, I'm sorry for that. 

Thanks again for the great completion engine!

**Comment by voldikss** [comment]
Sorry someone has already made a coc extension...

**Comment by airblade** [comment]
@voldikss Please could you link the coc extension?

**Comment by fannheyward** [comment]
Sorry for the late response. I've made the [coc-kite](https://www.npmjs.com/package/coc-kite) extension about week ago, and published the _compiled_ code to npmjs. Currently, completion/hover/definition/signature work with coc.nvim.

I've not public the source code on GitHub or anywhere else by now, cause there are still some bugs, also, I've never got your authorization. If you do not allow such behavior, I'll remove the npm package.

Sorry for trouble you guys, and thanks for Kite Engine.
