### ISSUE TITLE
Not working in dev container

### ISSUE THREAD

**Issue by cpoetter** [kiteco/vscode-plugin#267]
Hi,

I just installed Kite and the Kite extension for VS Code on my Mac. It is working really great!
I would also like to use it inside my dev container (https://code.visualstudio.com/docs/remote/containers). But unfortunately the extension always says "kite: not installed". 

Do I need for forward any ports in the docker compose file? Or change something else?

Thank you for your help!

**Comment by metalogical** [comment]
Subsumed by https://github.com/kiteco/issue-tracker/issues/250
