### ISSUE TITLE
moving from tab to tab

### ISSUE THREAD

**Issue by alcatraz5yz** [kiteco/vscode-plugin#272]
if I open the first python file, kite works perfectly fine,
but when I open a second file and go back and forth between those two python files,
kite stops working.

**Comment by its-dhung** [comment]
When you switch between files, do you still see the "kite" logo in the bottom right corner of VS Code?

**Comment by metalogical** [comment]
Closing due to age and lack of clarity on the issue. If more information is provided, we can reopen.
