### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by EdgarHarutyunyan02** [kiteco/vscode-plugin#277]
- Issue Type: `Bug`
- Extension Name: `kite`
- Extension Version: `0.109.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by metalogical** [comment]
please provide details about the issue you're experiencing
