### ISSUE TITLE
Does this not work in remote development mode?

### ISSUE THREAD

**Issue by thakkarparth007** [kiteco/vscode-plugin#286]
I installed Kite on my desktop just to check it out, but my code is on a remote machine. My workflow is editing the code using VSCode's remote development feature. Turns out Kite has to be installed on that machine as well. I'm not sure how it works, but can't my local Kite installation be used for remote development?

**Comment by mrmatos6837** [comment]
I second this!

**Comment by tgh19** [comment]
I third this!

**Comment by vivekpayasi** [comment]
I would totally love that!

I was trying to install the Kite engine in the remote Linux machine through terminal, but it doesn't seem to be working.

Let's hope it becomes available via local installation.

**Comment by cpoetter** [comment]
I would also really like this feature for dev container! 
https://github.com/kiteco/vscode-plugin/issues/267

**Comment by metalogical** [comment]
Subsumed by https://github.com/kiteco/issue-tracker/issues/250
