### ISSUE TITLE
Cannot uninstall the plugin

### ISSUE THREAD

**Issue by Katolus** [kiteco/vscode-plugin#288]
Every time I try to install the plugin it comes back again.

![flameshoot_2020-04-20-12-56-46](https://user-images.githubusercontent.com/20417569/79709950-dc763c00-8306-11ea-9233-105d9a15e339.png)

I tried removing the `kiteco.kite-0.110.0/` from `~/.vscode/extensions`, but reloading VSCode brings it up. What is this hacking?

**Comment by metalogical** [comment]
Hi @Katolus 

Have you tried removing the VS Code plugin via the plugins page in the Kite Copilot? You can visit kite://settings/plugins in your web browser, and then click "uninstall" to uninstall the plugin.

If you're still having trouble, let us know and we can work with you to diagnose the issue.

**Comment by Katolus** [comment]
Hi @metalogical 

I don't understand why you close the issue straightaway, but I don't know what you mean by the Kite Copilot. I haven't installed anything like that. I just installed the VSCode plugin and tried downloading the kite package, but decided not to as it was too big, so it hasn't finished. 

Even if I had something like that installed I don't understand why wouldn't it allow me to uninstall the plugin from the extension view?

**Comment by metalogical** [comment]
Hi @Katolus 

If you don't have Kite (the desktop app) installed, and VS Code is not letting you remove the Kite extension, then this must be an issue with the VS Code extension manager. I would recommend filing an issue on their repository.

**Comment by Katolus** [comment]
Hi @metalogical 

It is only a problem with your extension other plugins I can remove without a problem.
