### ISSUE TITLE
Extra paths.

### ISSUE THREAD

**Issue by CMLL** [kiteco/vscode-plugin#293]
Is there a way to let the extension know that it should index or analyse the code in a specific folder?

Like with the option "python.autoComplete.extraPaths"?

**Comment by metalogical** [comment]
for Python libraries that you have installed locally, you can follow the instructions here to let Kite know about their location:

https://help.kite.com/article/97-adding-libraries-from-pythonpath-to-the-kite-index

If this doesn't work, please file another issue with more details.
