### ISSUE TITLE
allow autocompletion for only 1 file extension while disabling others.

### ISSUE THREAD

**Issue by Abhirup-99** [kiteco/vscode-plugin#339]
e.g:
I want autocompletion only for .js/.ts file while disabling it for .HTML file bcoz it messes up with emmet.

**Comment by metalogical** [comment]
Hi @Abhirup-99 

This is possible. Just to get more information: how does the Kite plugin interfere with Emmet?

**Comment by Abhirup-99** [comment]
Thanks for the reply. In vs code, with emmet, and vs code autocompletion for the tags, kite is not generally required for both HTML and CSS files, but kite suggestions come at the top and for using emmet, I have to scroll down to get the emmet suggestion.
Also, can you suggest the procedure of how to achieve disabling for .HTML and .css files?
Lastly, kite autocompletion is great. Thanks for this.

**Comment by metalogical** [comment]
Note for implementer:

1. provide in-editor options to enable/disable per filetype
2. for disabled filetypes, show "Kite: disabled" in the status bar.
    * If we can add a tooltip (or similar), perhaps "Enable this file type in VS Code settings"

**Comment by tonycheang** [comment]
Hi @Abhirup-99, if you update to `v0.132.0` of the vscode plugin, you should be able to disable Kite completions for html and css with ` "kite.completions.disabledFileExtensions": [ ".css", ".html" ]` in your settings

**Comment by metalogical** [comment]
We have to revert the change temporarily in 0.133.0 as it is causing another issue. It will be reintroduced shortly.

**Comment by tonycheang** [comment]
Reintroduced in `0.134.0`, https://github.com/kiteco/vscode-plugin/commit/28b28c1cb6340c58b93391ee8053cf73c2847022
