### ISSUE TITLE
Kite window keeps popping up

### ISSUE THREAD

**Issue by elbaro** [kiteco/vscode-plugin#352]
Kite suddenly got unusable. Kite window + `You've been upgraded to a Kite Pro trial` noti keeps popping up even after I close them.

```
❯ pacman -Q kite          
kite 2.20200825.0-1
```

**Comment by metalogical** [comment]
Hi Elbaro,

Please upgrade Kite to a more recent version first, as the version you are running is very old. We typically release a new version of Kite approximately once a week – the latest version is 2.20201123.0.

The only supported installation mechanism is via https://www.kite.com/download/. The AUR package you are using is not maintained by us, and it seems very outdated.

If you still experience the issue after upgrading, then please re-open the issue with attached logs.
