### ISSUE TITLE
Steps to completely uninstall Kite from the system (including editors not asked to install) and request to fix automated uninstaller to not be confused with malware behavior

### ISSUE THREAD

**Issue by fititnt** [kiteco/vscode-plugin#375]
**I'm about to report the kiteco/vscode-plugin as a malware to Microsoft and very likely to do the same for every other extension supported by Kite it this issue is not handled with the necessary seriousness.** For places without an market place, like VIM, I'm likely to report on Reddit and/or ycombinator. And yes, I'm very serious about this.

I can understand, that, in good faith, software can have errors, and the Kite may have issues with the uninstaller, so as long as the developers of @kiteco show genuine interest to address these issues, I'm ok to wait at least few weeks, if not months. But for more short term it must have some type of explanation on how to immediately uninstall ALL files, and even startup ones that may let the system keep complaining for years that something is missing.

Note that developers can make errors, but [just close issues](https://github.com/kiteco/vscode-plugin/issues/288#issuecomment-617031852) or [blame the user as 'this is not my issue, ask to VSCode team'](https://github.com/kiteco/vscode-plugin/issues/288#issuecomment-617267596) is a sign of acting in bad faith and not just incompetence.

Also, not tested for others editors, but if the user did not marked as "Don't show this again", the every kite installation out there on VSCode may be sending user data AFTER installation for the Kite servers. So this is not just an issue to report to Microsoft, but an GDPR violation.

As for reference, this is the current how-to-uninstall-kite (including archived versions)
- https://help.kite.com/article/68-how-to-uninstall-kite
- https://web.archive.org/web/20210207211105/https://help.kite.com/article/68-how-to-uninstall-kite
- https://archive.vn/qpY5m

---

## Another example of how users have problem with uninstall

- Tried the steps described on <https://help.kite.com/article/68-how-to-uninstall-kite>, in special the "Quit Kite Next, you will need to quit Kite. You can do so from the menu bar icon." and the `rm -rf ~/.kite`
- Never asked to install the extension on Vim or any other place than VSCode.
- Restarted a few times the computer
- Results:

```bash
fititnt@bravo:/$ sudo find . -iname kite
[sudo] senha para fititnt: 
./home/fititnt/.local/share/kite
./home/fititnt/.local/share/kite/kite-v2.20210128.0/linux-unpacked/kite
./home/fititnt/.config/Kite
./home/fititnt/.vim/pack/kite
./home/fititnt/.vim/pack/kite/start/vim-plugin/autoload/kite
./home/fititnt/anaconda3/pkgs/spyder-4.1.5-py38_0/lib/python3.8/site-packages/spyder/plugins/completion/kite
```

![Captura de tela de 2021-02-10 19-02-06](https://user-images.githubusercontent.com/812299/107579498-fc4b5900-6bd3-11eb-9c31-995725c9fd26.png)
![Captura de tela de 2021-02-10 19-02-29](https://user-images.githubusercontent.com/812299/107579506-ffdee000-6bd3-11eb-9bec-f00d58910362.png)

Not only the extension keeps reinstalling again on VSCode without authorization, but also kite installed itself on several other programs that I never authorized. So the remove page is not even complete.

This issue on _kiteco/vim-plugin/issues/256 can not remove kite cleanly_ already was closed for comments. **This is very serious!** And the documentation does not cite in any place how to remove from VIM or Spyder. In fact, the documentation does not even cite that the Kite would be installed on new editors without proper authorization! So basically not only this is an privacy issue, but leave broken system.

----

Some issues already reported. For everyone reading, note that some were closed immediately and one from VIM comments were deleted and the thread closed.

- https://github.com/kiteco/vim-plugin/issues/256
- https://github.com/kiteco/vscode-plugin/issues/288#issuecomment-617031852
- https://github.com/kiteco/vim-plugin/issues/286
- https://github.com/kiteco/vim-plugin/issues/135
- https://github.com/kiteco/issue-tracker/issues/524
- https://github.com/kiteco/vim-plugin/issues/256
- https://github.com/kiteco/atom-plugin/issues/497
- https://github.com/kiteco/atom-plugin/issues/206
- https://github.com/kiteco/atom-plugin/issues/21
- https://news.ycombinator.com/item?id=13978457

**Comment by fititnt** [comment]
Quick copy of this page (https://github.com/kiteco/vscode-plugin/issues/375) if got deleted or censored:

- https://archive.vn/S03f4
- https://web.archive.org/web/20210210231230/https://github.com/kiteco/vscode-plugin/issues/375

**Comment by adamsmith** [comment]
Hi @fititnt, did you try to run the Linux uninstaller (`~/.local/share/kite/uninstall`) as mentioned in the help article you linked to? If so, what was the output? It should uninstall everything.

Note that Spyder is a special case: there is no plugin. Spyder detects when Kite is installed and it "just works", so there is nothing to uninstall. The existence of `./home/fititnt/anaconda3/pkgs/spyder-4.1.5-py38_0/lib/python3.8/site-packages/spyder/plugins/completion/kite` does not mean there is anything to uninstall.

Several of the links you references are out of date and no longer apply. I didn't look at all of them but definitely the bug mentioned in the old Hacker News thread was fixed a long time ago.

**Comment by fititnt** [comment]
### Closed because was heated?

![Captura de tela de 2021-02-10 22-39-06](https://user-images.githubusercontent.com/812299/107594562-f879ff80-6bf0-11eb-92d7-2fcd51ec5bba.png)

### Closed immediately and blamed the user?

@Katolus says 
>I don't understand why you close the issue straightaway, but I don't know what you mean by the Kite Copilot. I haven't installed anything like that. I just installed the VSCode plugin and tried downloading the kite package, but decided not to as it was too big, so it hasn't finished.
> 
> Even if I had something like that installed I don't understand why wouldn't it allow me to uninstall the plugin from the extension view?

![Captura de tela de 2021-02-10 22-39-57](https://user-images.githubusercontent.com/812299/107594584-062f8500-6bf1-11eb-83c5-c5a806213658.png)

### And this post here? @lUNuXl literally complain that this program install everywere, and cant remove

Also note how fast any complain about the mallware behavior is blamed to the user

![Captura de tela de 2021-02-10 22-44-05](https://user-images.githubusercontent.com/812299/107594787-9a015100-6bf1-11eb-88e1-352131260595.png)

**Comment by fititnt** [comment]
Here the updated copy of this page, in case got 'deleted' because of 'abusive comments': https://archive.vn/fqo8l

Also, for everyone of @kiteco: complaints like the one from @lUNuXl, aka someone who installed an application via VSCode, and then click to uninstall, and every time reboots the system the extension is there, is the definition of malware.

If the person click remove, the person wants to remove. Even if the `~/.local/share/kite/uninstall` failed (and it seems it fail not just for me) the mere fact that the extension keeps reinstalling on VSCode  is alone one serious issue to be reported about extensions on the VSCode market place.

### Where is the source code for the file ~/.local/share/kite/kite-v2.20210128.0/kite-update?

I would like to know where is the source code for this binary file. **And I'm very serious about this question.**

https://www.virustotal.com/gui/file/5f3a5cc0a7028d0f822d7b7f47f71954fc4a47ebf634f0a3ed06a80dd86ea4a4/detection

![Captura de tela de 2021-02-10 23-09-23](https://user-images.githubusercontent.com/812299/107595968-0df12880-6bf5-11eb-819b-66fe7ddd7c00.png)


For anyone reading this, every time the user startup the system, files named kite on `~/.config/systemd/user`,  (like `kite-autostart.service`, `kite-updater.service` and `kite-updater.timer`) are pinging back kite.com servers.

**Comment by lUNuXl** [comment]
> Also, for everyone of @kiteco: complaints like the one from @lUNuXl, aka someone who installed an application via VSCode, and then click to uninstall, and every time reboots the system the extension is there, is the definition of malware.

In my case I installed it in sublime text and I think it found its way into atom.
(I'm really not sure if I installed it there because I was trying to make DIY python IDE, maybe I was testing something with it in atom, I don't know).

**Comment by adamsmith** [comment]
Without going deep into details...

> Closed because was heated?
The deleted comments had cursing and attacks which is why we deleted them.

> Closed immediately and blamed the user?
I don't think we blamed the user — I think we made the suggestion that it was a problem with VS Code's plugin uninstallation mechanism or something was corrupt on the VS Code side.

> And this post here? @lUNuXl literally complain that this program install everywere, and cant remove
Please see his comment above & follow the thread there: kiteco/issue-tracker#524

> Where is the source code for the file ~/.local/share/kite/kite-v2.20210128.0/kite-update?
Kite is not open source.

I'm closing this issue and blocking the poster because it is not cohesive or productive.
