### ISSUE TITLE
Closing a whitelisting notification blacklists the project directory

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#53]
- Open a file which is not whitelisted and not yet blacklisted
- The VSCode plugin will show a notification which has a Close button
- A click on close blacklists the project dir ("C:\users\jansorg\" in my case) but it should blacklist the current file only

![vscode-file-blacklisting](https://user-images.githubusercontent.com/11473063/31215828-650f380a-a9b1-11e7-9beb-150ca0a4ec48.png)

**Comment by abe33** [comment]
I don't think that have been any different in the other plugins, we're blacklisting the directory returned by the `projectdir` endpoint, because otherwise a user would be bugged for every file of a project on which he doesn't care having kite running

**Comment by jansorg** [comment]
@abe33 As far as I can tell this is different than the in the other editors.
As far as I see blacklisting with the file's path adds the parent directory to the list in Kite's settings.

I just tested with Atom, a click on the X button to close the notification blacklisted "c:\users\jansorg\pycharmprojects\testpython\blacklisted" and not "c:\users\jansorg\".

PyCharm and Sublime work in the same way.

Could you update the "blacklist after user clicked on X" to blacklist the file?
Spec is at https://kite.quip.com/8xWpAmOqyh96/Behavioral-specification-Permissions#GZbACABGYBx.

We can discuss the best path to blackliste here, of course. But that will have to be done for all editors then. For now, VSCode should work the same way as the others do.
