### ISSUE TITLE
Clicking on a file link doesn't open it

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#54]
- Clicking on a link in the usages section or in the definition section doesn't open the file. In this example the file is available in the 'whitelisted' folder on the left.

![vscode-def-link](https://user-images.githubusercontent.com/11473063/31216671-c0fe0b70-a9b4-11e7-8c03-1623b59649f9.png)

**Comment by abe33** [comment]
Isn't there a `dog.py` tab at the top? So the file is already open, right?

**Comment by jansorg** [comment]
@abe33 
In the example the file was already open, I think.
I also tried with all tabs closed except for the sidebar. 

There doesn't seem to be any reaction to the click on the link.

**Comment by abe33** [comment]
So, it seems to be a recent change with VSCode APIs, now you have to explicitely show a text document after having created it...
