### ISSUE TITLE
UI translations?

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#55]
cc @tarakju 
I just noticed that VSCode is translated into German, but the Kite plugin is not. A mix of German/English is a bit unfortunate. I'm unsure whether the translations were added with the latest update or I just didn't notice.

@abe33 
It's probably similar with French, I gutess.
What do think about translating the user interface? Are translations easy or difficult to add?

**Comment by abe33** [comment]
I've seen nothing about it in [their docs](https://code.visualstudio.com/Search?q=local), I'm not even sure we can access the current selected locale to make our own system. I'll have to experiment to give a more definitive answer

**Comment by jansorg** [comment]
@abe33 Thanks for looking into this! I think that it's not very important right now. We should revisit this in the future, maybe during the preparations for the marketplace launch.

**Comment by adamsmith** [comment]
I agree with the above.  "Never say never" but we already have so many dimensions to the Kite product (editor, OS, network latencies, richness of code, local vs global api's, etc etc) that we don't have the resources to add another dimension of surface area.
