### ISSUE TITLE
Adding states to search panel

### ISSUE THREAD

**Issue by abe33** [kiteco/vscode-plugin#60]
- [x] No recorded searches before (@abmirayo how do we get these suggestions? Is it some new endpoint?)
- [x] Searches recorded
- [ ] Style changes to panel

**Comment by abe33** [comment]
@abmirayo I'm also a bit confused as to what exactly consider as a past search, given we're making searches as you type.

**Comment by abmirayo** [comment]
@abe33 

- For the no recorded searches before state, they'd be arbitrary hard-coded suggestions for now. I don't have a strong opinion to which ones. I don't think we need an endpoint for this, as this is just a way to get the user started very quickly on what kind of identifier they can type, and set expectations.

- With respect to *what* to consider a past search, I think that's a good question. I would suggest to determine this more accurately by having a timeout. So the condition for a search to be recorded would be: `identifier page is fetched and 1 second goes by without user switching to another query`. I think this would help with false positives, and I'd adjust this heuristic after testing it if 1 second is too short.

- I think it'd be a great idea for kited to handle this, so it can be reused by other editors and Electron. If for that to happen we have to wait weeks, I would bootstrap it for now by storing it temporarily in the plugin scope, the simplest way possible. If the simplest is to store it temporarily only while on that editor session, then I'd go for that. If it's not too hard to store it somewhere in the plugin that will persist across sessions, I would go for that.

**Comment by jansorg** [comment]
Closing, as it's old and apparently implemented
