### ISSUE TITLE
Status bar:

### ISSUE THREAD

**Issue by abe33** [kiteco/vscode-plugin#61]
Append to existing status text: 
- [x] {Shortcut} for docs. (When docs are available for that identifier / when it's a token)

**Comment by abe33** [comment]
@abmirayo It seems we won't be able to resolve which keybinding is currently associated with our command, in the case the user changed it, so it'll be great if could have some kind of fallback strategy

**Comment by abmirayo** [comment]
@abe33 

Yeah, makes sense. I think fallback should be `Docs available`.
