### ISSUE TITLE
"Open in Web" must encode id parameter value

### ISSUE THREAD

**Issue by jansorg** [kiteco/vscode-plugin#76]
The parameter value for "d" in http://localhost:46624/clientapi/desktoplogin?d=/docs/ID must be percent-encoded to make redirection work.

To reproduce:
1. Open "json.dumps" or any other python token in the sidebar
2. Choose "Open in Web" at the bottom of the screen
3. http://localhost:46624/clientapi/desktoplogin?d=/docs/python;json.dumps will be opened which then redirects to the wrong location https://westeurope.kite.com/docs/python . See https://github.com/kiteco/kiteco/issues/5065 for details.

**Comment by abe33** [comment]
Except that's already what we're doing, see https://github.com/kiteco/vscode-plugin/blob/master/src/urls.js#L107-L120 where we're using `escapeId`, which is defined below https://github.com/kiteco/vscode-plugin/blob/master/src/urls.js#L137-L139
