### ISSUE TITLE
Notes on develop branch

### ISSUE THREAD

**Issue by jlozano** [kiteco/vscode-plugin#9]
@abe33 reviewed the current `develop` branch, looking good! Some minor comments:
- In the status panel, the link for Account when a user is pro should link to `GET localhost:46624/clientapi/desktoplogin?d=/settings/acccount`, I think it currently links to `kite.com/pro` ?
- It looks like we are not showing the referral status message: https://kite.quip.com/rVcJA1bIqZny#QcWACAfPRvB or maybe I did not trigger it correctly?
- in the expand panel can we switch the ordering of the sections to: signature, parameters with types, popular patterns, **kwargs, docs, examples, usages, definition, links?

**Comment by abe33** [comment]
It has been updated in latest develop :)

**Comment by jlozano** [comment]
looking good! moving remaining comments to pull request
