### ISSUE TITLE
Autocomplete pop-up formatting seems broken and one parameter appears twice.

### ISSUE THREAD

**Issue by mwichary** [kiteco/vscode-plugin#96]
1. Type `json.dumps(`.

Result:
The formatting seems missing from the pop-up (you see a lot of backticks), plus *obj* is there twice?

I don't know if these two issues are related.

![image](https://user-images.githubusercontent.com/2061609/36559581-46d01f6e-17c3-11e8-8af5-35ad491ebf52.png)

**Comment by mwichary** [comment]
Update: The second parameter is the next-to-be-type parameter? It's changing as I type.

**Comment by abe33** [comment]
Actually that's not our plugin that returns that. Microsoft has its own python extension and is displaying its results in priority. It's up to the point that our extension's signature provider isn't even called. There's still no solution for this right now as Microsoft had made it clear they won't let third party extensions gain priority over their own extensions.

**Comment by mwichary** [comment]
Jeez, nice job Microsoft.
