### ISSUE TITLE
Docs for Cursor seems broken.

### ISSUE THREAD

**Issue by mwichary** [kiteco/vscode-plugin#97]
1. Type json.dumps()
2. Position cursor in the middle of dumps
3. Right click
4. Click on Kite: Docs For Cursor in the context menu

Result:
![image](https://user-images.githubusercontent.com/2061609/36560545-ddabfe56-17c5-11e8-9aed-7c619cb67aab.png)

Expected:
The thing that shows up when I hover over it and click more, e.g.
![image](https://user-images.githubusercontent.com/2061609/36560614-134bb2fe-17c6-11e8-81aa-516021f3df2b.png)

**Comment by abe33** [comment]
Hi @mwichary, 

I don't seem to reproduce that issue: 
![kite-context-menu](https://user-images.githubusercontent.com/247140/36971249-7db18d3c-206b-11e8-9f51-ff0cbeadc29e.gif)

Any additional info appreciated, I'll look into it in the meantime.

**Comment by mwichary** [comment]
@abe33 Hi! I’m looking at this right now and it’s failing in the same way. Let me know if I can help gather some more data.
